---

- name: Execute apt tasks
  import_tasks: apt.yml
  tags: ['apt']

- name: Download fzf
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf

- name: Install fzf
  ansible.builtin.shell: ~/.fzf/install
